src/cart/urls.py
from django.urls import path


from cart.views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view
)

urlpatterns = [

    path('',cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success/', checkout_done_view, name='success'),

]

src/ecommerce/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from .views import home_page,about_page,contact_page
from accounts.views import LoginView, RegisterView, guest_register,logout_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from cart.views import cart_detail_api_view
from billing.views import payment_method_view, payment_method_create_view

from django.conf import settings
from django.conf.urls.static import static

from cart.views import cart_home

urlpatterns = [ 
    path('products', include(('product.urls', 'products' ), namespace='products' )),
    path('search', include(('search.urls', 'search' ), namespace='search' )),
    path('cart/', include(('cart.urls', 'cart' ), namespace='cart' )),
    
    path('api/cart', cart_detail_api_view, name='api-cart'),
    path('', home_page, name='home'),
    path('about', about_page, name='about'),
    path('contact', contact_page, name='contact'),
    path('checkout/address/create_view', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/guest/', guest_register, name='guest_register'),
    path('payment/method-createview', payment_method_create_view, name='payment-method-endpoint'),
    path('billing/payment-method/', payment_method_view, name='billing-payment-method'),
    path('logout/', logout_view, name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('logout/', LogoutView.as_view(next_page='/custom-page/'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('admin/', admin.site.urls),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

src/product/urls.py
from django.urls import path

from product.views import (
    ProductListView, 

    ProductDetailSlugView,
)

urlpatterns = [

    path('',ProductListView.as_view(), name='list'),
    path('<slug:slug>', ProductDetailSlugView.as_view(), name='detail'),

]

src/templates/Base/css.html
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href='{% static " css/main.css"%}'>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">


<!-- <link rel="stylesheet" href="{% static 'css/checkout-stripe.css' %}"> -->

src/templates/Base/js.html
{% load static %}


<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- jQuery Confirm CSS -->

<!-- jQuery Confirm JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>


<script src="{% static 'js/ecommerce.js' %}"></script>
<script src="{% static 'js/csrf_ajax.js' %}"></script>



<script src="https://js.stripe.com/v3/"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.15/jsrender.js" integrity="sha512-O/3/A3yweFQg8fGt8BkFHj9S7AK6MbVz9Brq/LdWMAePl01O7Ykx31oZJpHKU/oT6B1vGYj9jgWbH4g1Y5rzaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

src/templates/Base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as products_list_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'contact' as contact_url %}
{% url 'cart:home' as  cart_url %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{ brand_name}} {% else %} Malz eCommerce {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item " >
          <a class="nav-link {% if request.path == home_url %} active {% endif %}" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
          <a class="nav-link" href="{{ contact_url }}">contact</a>
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div> -->
        </li>
        <li class="nav-item {% if request.path == products_list_url %} active {% endif %}">
          <a class="nav-link " href="{{ products_list_url }}">products</a>
        </li>
        <li class="nav-item {% if request.path == about_url %} active {% endif %}">
            <a class="nav-link" href="{{ about_url }}">About</a>
        </li>
        {% if request.user.is_authenticated %}
        <form method="post">
          <li class="nav-item {% if request.path == login_url %} active {% endif %}">
            <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
        </form>
            
        {% else %}
            <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            <li class="nav-item {%if request.path == register_url%} active {% endif %}">
                <a class="nav-link" href="{{register_url}}">Register</a>
            </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
          <a class="nav-link" href="{{ cart_url }}"> <span class="navbar-cart-count"> {{ request.session.cart_items }} </span><i class="fa fa-shopping-cart" aria-hidden="true"></i> </a>
      </li>
      </ul>
      {% include 'search/snippets/search_form.html'%}
      </form>
    </div>
  </nav>